"""Configurable Markdown report templates using Jinja2.

Provides multiple report formats for synthesis output:
- **survey**: Comprehensive survey-style report (default)
- **gap_analysis**: Focus on research gaps and open questions
- **lit_review**: Concise literature review table format
- **executive**: Short executive summary

Deep Research Report §B4: Report template system.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from pathlib import Path

from jinja2 import BaseLoader, Environment

from research_pipeline import __version__
from research_pipeline.models.summary import CrossPaperSynthesisRecord, SynthesisReport

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Template definitions
# ---------------------------------------------------------------------------

_SURVEY_TEMPLATE = """\
# Survey: {{ report.topic }}

*Generated by research-pipeline v{{ version }} on {{ timestamp }}*
*{{ report.paper_count }} papers analyzed*

## 1. Overview

This survey synthesizes findings from {{ report.paper_count }} papers on
**{{ report.topic }}**.

## 2. Key Agreements
{% for a in report.agreements %}
### 2.{{ loop.index }}. {{ a.claim }}

Supporting papers: {{ a.supporting_papers | join(', ') }}
{% for e in a.evidence %}
> {{ e.quote }} *({{ e.chunk_id }})*
{% endfor %}
{% endfor %}
{% if not report.agreements %}
No cross-paper agreements identified.
{% endif %}

## 3. Disagreements & Debates
{% for d in report.disagreements %}
### 3.{{ loop.index }}. {{ d.topic }}
{% for paper_id, position in d.positions.items() %}
- **{{ paper_id }}**: {{ position }}
{% endfor %}
{% endfor %}
{% if not report.disagreements %}
No disagreements identified.
{% endif %}

## 4. Open Questions
{% for q in report.open_questions %}
{{ loop.index }}. {{ q }}
{% endfor %}
{% if not report.open_questions %}
No open questions identified.
{% endif %}

## 5. Paper Summaries
{% for p in report.paper_summaries %}
### {{ p.title }} ({{ p.arxiv_id }})

**Objective**: {{ p.objective }}

**Methodology**: {{ p.methodology }}

**Key Findings**:
{% for f in p.findings %}
- {{ f }}
{% endfor %}

**Limitations**:
{% for l in p.limitations %}
- {{ l }}
{% endfor %}
{% if p.uncertainties %}

**Uncertainties**: {{ p.uncertainties | join('; ') }}
{% endif %}
---
{% endfor %}

## References
{% for p in report.paper_summaries %}
{{ loop.index }}. {{ p.title }} ({{ p.arxiv_id }}{{ p.version }})
{% endfor %}
"""

_GAP_ANALYSIS_TEMPLATE = """\
# Gap Analysis: {{ report.topic }}

*Generated by research-pipeline v{{ version }} on {{ timestamp }}*
*{{ report.paper_count }} papers analyzed*

## Research Gaps & Open Questions

{% for q in report.open_questions %}
### Gap {{ loop.index }}: {{ q }}

{% endfor %}
{% if not report.open_questions %}
No research gaps identified from the analyzed papers.
{% endif %}

## Contested Areas
{% for d in report.disagreements %}
### {{ d.topic }}

| Paper | Position |
|-------|----------|
{% for paper_id, position in d.positions.items() %}
| {{ paper_id }} | {{ position }} |
{% endfor %}
{% endfor %}

## Coverage Matrix

| Paper | Objective | Methodology | # Findings | # Limitations |
|-------|-----------|-------------|------------|---------------|
{% for p in report.paper_summaries %}
| {{ p.arxiv_id }} | {{ p.objective[:60] }}{% if p.objective|length > 60 %}...{% endif %} | {{ p.methodology[:40] }}{% if p.methodology|length > 40 %}...{% endif %} | {{ p.findings|length }} | {{ p.limitations|length }} |
{% endfor %}

## Established Consensus
{% for a in report.agreements %}
- **{{ a.claim }}** ({{ a.supporting_papers|length }} papers)
{% endfor %}
"""

_LIT_REVIEW_TEMPLATE = """\
# Literature Review: {{ report.topic }}

*Generated by research-pipeline v{{ version }} on {{ timestamp }}*

## Summary Table

| # | Paper | Objective | Method | Key Finding |
|---|-------|-----------|--------|-------------|
{% for p in report.paper_summaries %}
| {{ loop.index }} | {{ p.title }} ({{ p.arxiv_id }}) | {{ p.objective[:50] }}{% if p.objective|length > 50 %}...{% endif %} | {{ p.methodology[:40] }}{% if p.methodology|length > 40 %}...{% endif %} | {{ p.findings[0] if p.findings else 'N/A' }} |
{% endfor %}

## Themes

### Agreements
{% for a in report.agreements %}
- {{ a.claim }}
{% endfor %}

### Disagreements
{% for d in report.disagreements %}
- **{{ d.topic }}**: {{ d.positions.values()|list|join(' vs. ') }}
{% endfor %}

### Open Questions
{% for q in report.open_questions %}
- {{ q }}
{% endfor %}
"""

_EXECUTIVE_TEMPLATE = """\
# Executive Summary: {{ report.topic }}

*{{ report.paper_count }} papers | Generated {{ timestamp }}*

## Key Findings

{% for a in report.agreements %}
- **{{ a.claim }}** — supported by {{ a.supporting_papers|length }} paper(s)
{% endfor %}

## Active Debates

{% for d in report.disagreements %}
- {{ d.topic }}
{% endfor %}
{% if not report.disagreements %}
No active debates identified.
{% endif %}

## Research Gaps

{% for q in report.open_questions %}
{{ loop.index }}. {{ q }}
{% endfor %}
{% if not report.open_questions %}
No gaps identified.
{% endif %}
"""

_STRUCTURED_SYNTHESIS_TEMPLATE = """\
# Structured Research Synthesis: {{ report.topic }}

*Generated by research-pipeline v{{ version }} on {{ timestamp }}*
*{{ report.corpus|length }} papers analyzed*

## Executive Summary

This synthesis is generated from Step 1 extraction records. It preserves
traceability, assumptions, contradictions, and conditional design implications
without selecting an architecture.

## Scope and Corpus

| Paper | Title | Year | Venue |
|-------|-------|------|-------|
{% for p in report.corpus %}
| {{ p.paper_id }} | {{ p.title }} | {{ p.year }} | {{ p.venue }} |
{% endfor %}

## Methodology
{% for item in report.methodology %}
- {{ item }}
{% endfor %}

## Taxonomy of Approaches
{% for f in report.taxonomy %}
- **{{ f.confidence }}** {{ f.finding }} [{{ f.supporting_papers|join(', ') }}]
{% endfor %}
{% if not report.taxonomy %}
No taxonomy entries identified.
{% endif %}

## Evidence Matrix

| Paper | Methods | Results | Assumptions | Limitations |
|-------|---------|---------|-------------|-------------|
{% for row in report.evidence_matrix %}
| {{ row.paper_id }} | {{ row.methods }} | {{ row.results }} | {{ row.assumptions }} | {{ row.limitations }} |
{% endfor %}

## Recurring Mechanisms and Patterns
{% for f in report.recurring_patterns %}
- **{{ f.confidence }}** {{ f.finding }} [{{ f.supporting_papers|join(', ') }}]
{% endfor %}
{% if not report.recurring_patterns %}
No recurring patterns identified.
{% endif %}

## Assumption Map
{% for a in report.assumption_map %}
- **{{ a.assumption_id }}** {{ a.assumption }} [{{ a.source_papers|join(', ') }}]
{% endfor %}
{% if not report.assumption_map %}
No assumptions identified.
{% endif %}

## Contradiction Map
{% for c in report.contradiction_map %}
- **{{ c.contradiction_id }}** {{ c.topic }}
{% for paper_id, position in c.positions.items() %}
  - {{ paper_id }}: {{ position }}
{% endfor %}
{% endfor %}
{% if not report.contradiction_map %}
No contradictions identified.
{% endif %}

## Evidence Strength Map
{% for f in report.evidence_strength_map %}
- **{{ f.confidence }}** {{ f.finding }} [evidence: {{ f.evidence_ids|join(', ') }}]
{% endfor %}

## Operational Implications
{% for f in report.operational_implications %}
- **{{ f.confidence }}** {{ f.finding }}
{% endfor %}

## Production Readiness
{% for f in report.production_readiness %}
- **{{ f.confidence }}** {{ f.finding }}
{% endfor %}

## Reusable Mechanism Inventory
{% for m in report.reusable_mechanism_inventory %}
- **{{ m.mechanism_id }}** {{ m.name }}: {{ m.description }} [{{ m.source_papers|join(', ') }}]
{% endfor %}

## Design Implications
{% for f in report.design_implications %}
- **{{ f.confidence }}** {{ f.finding }}
{% endfor %}

## Unresolved Questions
{% for q in report.unresolved_questions %}
- {{ q }}
{% endfor %}

## Risk Register
{% for f in report.risk_register %}
- **{{ f.confidence }}** {{ f.finding }}
{% endfor %}

## Traceability Appendix

| Item | Type | Papers | Evidence | Confidence |
|------|------|--------|----------|------------|
{% for row in report.traceability_appendix %}
| {{ row.item_id }} | {{ row.item_type }} | {{ row.papers }} | {{ row.evidence_ids }} | {{ row.confidence }} |
{% endfor %}
"""

# Registry of built-in templates
TEMPLATES: dict[str, str] = {
    "structured_synthesis": _STRUCTURED_SYNTHESIS_TEMPLATE,
    "survey": _SURVEY_TEMPLATE,
    "gap_analysis": _GAP_ANALYSIS_TEMPLATE,
    "lit_review": _LIT_REVIEW_TEMPLATE,
    "executive": _EXECUTIVE_TEMPLATE,
}


def list_templates() -> list[str]:
    """Return legacy template names kept stable for compatibility."""
    return sorted(name for name in TEMPLATES if name != "structured_synthesis")


def render_report(
    report: SynthesisReport | CrossPaperSynthesisRecord,
    template_name: str = "survey",
    custom_template: str | None = None,
) -> str:
    """Render a synthesis report using a named or custom Jinja2 template.

    Args:
        report: The synthesis report to render.
        template_name: Name of a built-in template (survey, gap_analysis,
            lit_review, executive).
        custom_template: Optional custom Jinja2 template string. If provided,
            overrides *template_name*.

    Returns:
        Rendered Markdown string.

    Raises:
        ValueError: If *template_name* is not recognized and no custom
            template is provided.
    """
    if custom_template is not None:
        tmpl_str = custom_template
    elif template_name in TEMPLATES:
        tmpl_str = TEMPLATES[template_name]
    else:
        raise ValueError(
            f"Unknown template {template_name!r}. Available: {list_templates()}"
        )

    env = Environment(loader=BaseLoader(), autoescape=False)  # nosec B701
    template = env.from_string(tmpl_str)

    timestamp = datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M UTC")
    rendered = template.render(
        report=report,
        version=__version__,
        timestamp=timestamp,
    )
    return rendered.strip() + "\n"


def render_report_to_file(
    report: SynthesisReport | CrossPaperSynthesisRecord,
    output_path: Path,
    template_name: str = "survey",
    custom_template: str | None = None,
) -> None:
    """Render a synthesis report and write to a file.

    Args:
        report: The synthesis report to render.
        output_path: Destination Markdown file path.
        template_name: Name of a built-in template.
        custom_template: Optional custom Jinja2 template string.
    """
    content = render_report(report, template_name, custom_template)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    logger.info(
        "Rendered %s report to %s",
        template_name if custom_template is None else "custom",
        output_path,
    )
