"""MCP tool implementations, split by domain (issue #108 part 2).

This package re-exports every public tool function and the shared
error/helper surface so that ``from research_pipeline.mcp_server.tools
import <name>`` resolves exactly as it did when this was a single module.
"""

from __future__ import annotations

from research_pipeline.mcp_server.tools._common import (
    McpToolError,
    _backend_kwargs,
    _get_run_root,
    _log_info,
    _raise_tool_error,
    _report_progress,
    _resolve_latest_run_id,
    _resolve_run_id,
    _resolve_workspace,
    _sanitize_candidates,
    _scrub_exc,
    logger,
)
from research_pipeline.mcp_server.tools.brief import (
    brief_export_obsidian_tool,
    brief_generate_daily_tool,
    brief_generate_dossier_tool,
    brief_poll_sources_tool,
    brief_rank_events_tool,
    brief_record_feedback_tool,
    brief_run_tool,
    brief_validate_report_tool,
    brief_weekly_synthesis_tool,
)
from research_pipeline.mcp_server.tools.confidence import (
    adaptive_stopping_tool,
    analyze_claims_tool,
    confidence_layers_tool,
    score_claims_tool,
)
from research_pipeline.mcp_server.tools.conversion import (
    convert_file,
    convert_fine,
    convert_pdfs,
    convert_rough,
    list_backends,
)
from research_pipeline.mcp_server.tools.evaluation import (
    blinding_audit_tool,
    coherence_tool,
    consolidation_tool,
    dual_metrics_tool,
    evaluate_tool,
    search_tools,
)
from research_pipeline.mcp_server.tools.knowledge_graph import (
    kg_ingest_tool,
    kg_quality_tool,
    kg_query_tool,
    kg_stats_tool,
)
from research_pipeline.mcp_server.tools.memory import (
    cbr_lookup_tool,
    cbr_retain_tool,
    memory_episodes_tool,
    memory_search_tool,
    memory_stats_tool,
)
from research_pipeline.mcp_server.tools.pipeline import (
    compare_runs,
    compute_semantic_scores,
    download_pdfs,
    expand_citations,
    extract_content,
    get_run_manifest,
    manage_index,
    plan_topic,
    query_eval_log,
    record_feedback,
    run_pipeline,
    screen_candidates,
    search,
    summarize_papers,
    verify_stage,
)
from research_pipeline.mcp_server.tools.quality import (
    aggregate_evidence_tool,
    analyze_papers,
    cite_context_tool,
    cluster_tool,
    enrich_tool,
    evaluate_quality,
    export_bibtex_tool,
    export_html_tool,
    gate_info_tool,
    get_venue_tier,
    horizon_metric_tool,
    model_routing_info_tool,
    report_tool,
    rrp_diagnostic_tool,
    validate_report,
    watch_tool,
)

__all__ = [
    "McpToolError",
    "_backend_kwargs",
    "_get_run_root",
    "_log_info",
    "_raise_tool_error",
    "_report_progress",
    "_resolve_latest_run_id",
    "_resolve_run_id",
    "_resolve_workspace",
    "_sanitize_candidates",
    "_scrub_exc",
    "adaptive_stopping_tool",
    "aggregate_evidence_tool",
    "analyze_claims_tool",
    "analyze_papers",
    "blinding_audit_tool",
    "brief_export_obsidian_tool",
    "brief_generate_daily_tool",
    "brief_generate_dossier_tool",
    "brief_poll_sources_tool",
    "brief_rank_events_tool",
    "brief_record_feedback_tool",
    "brief_run_tool",
    "brief_validate_report_tool",
    "brief_weekly_synthesis_tool",
    "cbr_lookup_tool",
    "cbr_retain_tool",
    "cite_context_tool",
    "cluster_tool",
    "coherence_tool",
    "compare_runs",
    "compute_semantic_scores",
    "confidence_layers_tool",
    "consolidation_tool",
    "convert_file",
    "convert_fine",
    "convert_pdfs",
    "convert_rough",
    "download_pdfs",
    "dual_metrics_tool",
    "enrich_tool",
    "evaluate_quality",
    "evaluate_tool",
    "expand_citations",
    "export_bibtex_tool",
    "export_html_tool",
    "extract_content",
    "gate_info_tool",
    "get_run_manifest",
    "get_venue_tier",
    "horizon_metric_tool",
    "kg_ingest_tool",
    "kg_quality_tool",
    "kg_query_tool",
    "kg_stats_tool",
    "list_backends",
    "logger",
    "manage_index",
    "memory_episodes_tool",
    "memory_search_tool",
    "memory_stats_tool",
    "model_routing_info_tool",
    "plan_topic",
    "query_eval_log",
    "record_feedback",
    "report_tool",
    "rrp_diagnostic_tool",
    "run_pipeline",
    "score_claims_tool",
    "screen_candidates",
    "search",
    "search_tools",
    "summarize_papers",
    "validate_report",
    "verify_stage",
    "watch_tool",
]
